name: Check Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        uses: jesusvasquez333/verify-pr-label-action@v1.1.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'major, minor, patch, skip-release'