name: CI

on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Skip CI
      uses: veggiemonk/skip-commit@master
      env:
        COMMIT_FILTER: skip ci
      
    - name: Install dependencies and run tests
      run: |
        npm install
        npx lerna exec npm install && npx lerna link convert
        npm run test
  
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Prepare repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git checkout "${GITHUB_REF:11}"
        git remote rm origin
        git remote add origin "https://$GH_TOKEN@github.com/drawbotics/drylus.git"
        git fetch origin
        git branch --set-upstream-to origin/master
        
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git remote -v
        git checkout -- .
        npm run release