name: CI

on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up node 9
        uses: actions/setup-node@v1
        with:
          node-version: '9.x'
        
      - name: npm install and test
        run: |
          npm install
          npm test