name: CI

on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: npm install and test
        run: |
          npm install
          npx lerna exec npm install && npx lerna link convert
          npm run test