name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[skip ci]') == false
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '9.x'

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: |
          npm install
          npx lerna link convert
          npx lerna exec --stream -- npm install
          npm run build