name: Docs

on:
  push:
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build styleguide docs
        run: |
          npm install
          npm run build:styleguide