name: Docs

on:
  push:
    branches:    
      - master

jobs:
  build-docs:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up node 9
        uses: actions/setup-node@v1
        with:
          node-version: '9.x'

      - name: Build styleguide docs
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

        run: |
          npm install
          npm run build

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_BRANCH: 'master'