name: Docs

on:
  push:
    branches:    
      - master
    paths-ignore:
    - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: Build styleguide docs
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

        run: |
          npm install
          npx lerna exec npm install && npx lerna link convert
          npm run build

      - name: Commit changes
        run: npm run publish:styleguide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}