name: Docs

on:
  push:
    branches:    
      - master

jobs:
  build-docs:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up node 10
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Build styleguide docs
        run: |
          npm install
          npm run build:styleguide

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_BRANCH: 'master'