name: CI

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '*'

jobs:
  notify:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: frankjuniorr/github-create-release-action@master
