name: CI

on: push

jobs:
  notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: 'drylus-releases'
          SLACK_USERNAME: Drylus
          SLACK_ICON : 'https://www.drawbotics.com/favicon-32x32.png'
          SLACK_COLOR: '#3DB5D0'
          SLACK_TITLE: New release
          SLACK_MESSAGE: 'Check the changelog: https://www.notion.so/drawbotics/Changelog-Design-System-07f11499fda24ddea5c368d5133b08c4'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
