name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@drawbotics'
    - name: Install dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}

    - name: Generate Changelog
      if: "!contains(github.ref, 'beta')"
      run: |
        npx auto changelog --dry-run | grep -vE "lerna notice|lerna success|New Release Notes" > ${{ github.workflow }}-CHANGELOG.md
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Pre-release
      uses: softprops/action-gh-release@v1
      if: "contains(github.ref, '-')"
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: "!contains(github.ref, 'beta')"
      with:
        body_path: ${{ github.workflow }}-CHANGELOG.md
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}