name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm install

    - name: Generate Changelog
      run: |
        npx auto changelog --dry-run | grep -vE "lerna notice|lerna success|New Release Notes" > ${{ github.workflow }}-CHANGELOG.md
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workflow }}-CHANGELOG.md
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}